#!/bin/sh

#SBATCH --job-name="diff mask"
#SBATCH --partition=a100
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=50G
#SBATCH --time=03-00:00:00 
#SBATCH --gpus=1
#SBATCH -o slurm.%N.%j.out 
#SBATCH -e slurm.%N.%j.err

free_port=$(exec /mnt/fast/nobackup/users/ad02037/anaconda3/envs/sith/envs/sith/bin/python -c "import socket; s = socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.bind(('', 0)); print(s.getsockname()[1]); s.close()")


wandb disabled;
exec /mnt/fast/nobackup/users/ad02037/anaconda3/envs/sith/bin/accelerate launch /mnt/fast/nobackup/users/ad02037/SiTH_fork/diffusion/train_obj_diffusion.py  --output_dir /mnt/fast/nobackup/users/ad02037/out_inpainting --conditioning_channels 1 --white_background --validation --config /mnt/fast/nobackup/users/ad02037/SiTH_fork/diffusion/config.yaml --input_path /mnt/fast/datasets/ucdatasets/synHOR/sequences --input_path_test /mnt/fast/datasets/ucdatasets/synHOR/sequences --batch_size 6 --train_batch_size 6 --exp_name diff_mask_slurm --num_validation_images 5
