#!/bin/sh

#SBATCH --job-name="nnormal mask"
#SBATCH --partition=a100
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=50G
#SBATCH --time=03-00:00:00 
#SBATCH --gpus=1
#SBATCH -o slurm.%N.%j.out 
#SBATCH -e slurm.%N.%j.err

free_port=$(exec /mnt/fast/nobackup/users/mp01223/anaconda/envs/icon2/bin/python3 -c "import socket; s = socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.bind(('', 0)); print(s.getsockname()[1]); s.close()")


wandb disabled;
exec /mnt/fast/nobackup/users/mp01223/anaconda/envs/diffusion/bin/accelerate launch /mnt/fast/nobackup/scratch4weeks/mp01223/inpainting/SiTH/diffusion/train.py  --output_dir /mnt/fast/nobackup/scratch4weeks/mp01223/inpainting/cvpr1/sith_model --conditioning_channels 3 --only_normal --white_background --validation --config /mnt/fast/nobackup/scratch4weeks/mp01223/inpainting/SiTH/diffusion/config.yaml --input_path /mnt/fast/nobackup/scratch4weeks/mp01223/synHOI_inpainting_final/RENDER --input_path_test /mnt/fast/nobackup/scratch4weeks/mp01223/synHOI_inpainting_final_test_red/RENDER --batch_size 6 --exp_name only_normal_slurm --num_validation_images 5  --validation_steps 2500
